language: generic 
sudo: required
services:
    - docker

before_install:
    -docker build -t dschonholtz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dschonholtz/react-test npm test

after_success:
    - docker build -t dschonholtz/multi-client ./client
    - docker build -t dschonholtz/multi-nginx ./nginx
    - docker build -t dschonholtz/multi-server ./server
    - docker build -t dschonholtz/multi-worker ./worker
    # login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dschonholtz/multi-client
    - docker push dschonholtz/multi-nginx
    - docker push dschonholtz/multi-server
    - docker push dschonholtz/multi-worker