language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t schonholtzd/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true schonholtzd/react-test npm test

after_success:
    - docker build -t schonholtzd/multi-client ./client
    - docker build -t schonholtzd/multi-nginx ./nginx
    - docker build -t schonholtzd/multi-server ./server
    - docker build -t schonholtzd/multi-worker ./worker
    # login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
    - docker push schonholtzd/multi-client
    - docker push schonholtzd/multi-nginx
    - docker push schonholtzd/multi-server
    - docker push schonholtzd/multi-worker